# just_dance_rehab_config.py
# Configuracion central de ejercicios de rehabilitacion fisica

REHAB_EXERCISE_CONFIGS = {
'brazo doblado': {'id': 'brazo doblado',
                    'name': 'Flexión de Codo',
                   'body_region': 'CODO',
                   'side': 'right',
                   'reference_video': 'rehab_references/videos/brazo doblado_valido.mp4',
                   'trajectory_json': 'rehab_references/trajectories/brazo doblado.json',
                   'tracking_type': 'pose33',
                   'landmark_schema': 'mediapipe_pose_33',
                   'evaluation_mode': 'trajectory',
                   'validation_strategy': 'single_joint_primary',
                   'primary_angle': 'right_elbow_flexion_3d',
                   'direction': 'decreasing',
                   'active_angles': ['right_elbow_flexion_3d', 'trunk_lean_2d', 'shoulder_alignment_2d'],
                   'required_landmarks': ['right_shoulder', 'right_elbow', 'right_wrist'],
                   'optional_landmarks': ['right_wrist', 'left_shoulder', 'left_hip'],
                   'compensation_rules': [],
                   'start_ranges': {'right_elbow_flexion_3d': [153.34, 173.34]},
                   'target_ranges': {'right_elbow_flexion_3d': [68.44, 88.44]},
                   'safe_ranges': {'right_elbow_flexion_3d': [58.44, 180.0]},
                   'rep_duration': 6.0,
                   'key_pose_offset': 3.0,
                   'valid_rep_score': 70,
                    'min_tracking_confidence': 0.2,
                    'body_parts': ['CODO', 'BRAZO DERECHO'],
                   'artist': 'Rehabilitacion fisica - codo',
                   'color': (100, 200, 100),
                   'complexity': 'BAJO',
                   'feedback': {'waiting_start': 'Extiende el brazo en posicion inicial.',
                                'go_to_target': 'Dobla el codo lentamente.',
                                'return_start': 'Extiende el codo con control.',
                                'rep_valid': 'Repeticion valida.',
                                'rep_invalid': 'Repeticion no valida. Revisa el rango de movimiento.',
                                'lost_tracking': 'Ajusta la camara para ver bien el movimiento.'},
                    'angle_smoothing': 0.4,
                    'auto_calibrate': True,
                    'calib_frames': 15,
                    'calib_max_jitter': 12.0,
                    'target_delta': 65.0,
                    'return_tolerance': 15.0,
                    'safe_margin': 100.0,
                    'min_frames_in_start': 4,
                    'min_frames_in_target': 4,
                    'min_frames_return': 3},
  'cuello atras': {'id': 'cuello atras',
                   'name': 'Extension Cervical',
                  'body_region': 'CUELLO',
                  'side': 'right',
                  'reference_video': 'rehab_references/videos/cuello atras_valido.mp4',
                  'trajectory_json': 'rehab_references/trajectories/cuello atras.json',
                  'tracking_type': 'pose33',
                  'landmark_schema': 'mediapipe_pose_33',
                  'evaluation_mode': 'trajectory',
                  'validation_strategy': 'neck_primary_only',
                  'primary_angle': 'neck_extension_side_2d',
                  'direction': 'decreasing',
                  'active_angles': ['neck_extension_side_2d', 'shoulder_width_2d'],
                  'required_landmarks': ['nose', 'right_shoulder', 'left_shoulder'],
                  'optional_landmarks': ['right_ear', 'left_ear'],
                  'compensation_rules': [],
                  'angle_smoothing': 0.65,
                  'auto_calibrate': True,
                  'calib_frames': 18,
                  'calib_max_jitter': 6.0,
                  'target_delta': 20.0,
                  'return_tolerance': 14.0,
                  'safe_margin': 8.0,
                  'start_ranges': {'neck_extension_side_2d': [35.0, 68.0]},
                  'target_ranges': {'neck_extension_side_2d': [20.0, 34.0]},
                  'safe_ranges': {'neck_extension_side_2d': [0.0, 78.0]},
                  'rep_duration': 6.0,
                  'key_pose_offset': 3.0,
                  'valid_rep_score': 70,
                  'min_tracking_confidence': 0.45,
                  'body_parts': ['CUELLO'],
                  'artist': 'Rehabilitacion fisica - cuello',
                  'color': (220, 130, 80),
                  'complexity': 'BAJO',
                  'feedback': {'waiting_start': 'Coloca la cabeza neutral, de lado a la camara.',
                               'go_to_target': 'Lleva solo la cabeza hacia atras lentamente.',
                               'return_start': 'Regresa la cabeza a neutral y mantenla un momento.',
                               'rep_valid': 'Repeticion valida.',
                               'rep_invalid': 'No valido. Mantente de lado y mueve solo cuello/cabeza.',
                               'lost_tracking': 'Camara debe ver nariz y ambos hombros.',
                               'calibrating': 'Mantente quieto de lado con cabeza neutral para calibrar.'},
                  'min_frames_in_target': 4,
                  'min_frames_in_start': 3,
                  'min_frames_return': 3,
                  'gate_ranges': {'shoulder_width_2d': [0.0, 0.22]},
                  'gate_feedback': 'Ponte de lado a la camara. No gires el cuerpo ni abras los hombros.'},
  'cuello izq': {'id': 'cuello izq',
                 'name': 'Inclinación Cervical (dere – frontal)',
                'body_region': 'CUELLO',
                'side': 'left',
                'reference_video': 'rehab_references/videos/cuello izq_valido.mp4',
                'trajectory_json': 'rehab_references/trajectories/cuello izq.json',
                'tracking_type': 'pose33',
                'landmark_schema': 'mediapipe_pose_33',
                'evaluation_mode': 'trajectory',
                'validation_strategy': 'neck_primary_only',
                'primary_angle': 'neck_lateral_signed_2d',
                'direction': 'decreasing',
                'active_angles': ['neck_lateral_signed_2d', 'head_lateral_signed_2d', 'neck_deviation_2d'],
                'required_landmarks': ['nose', 'left_shoulder', 'right_shoulder', 'right_hip'],
                'optional_landmarks': ['left_ear', 'right_ear',
                                       'left_hip'],
                'compensation_rules': [],
                'start_ranges': {'neck_lateral_signed_2d': [-12.0, 12.0]},
                'target_ranges': {'neck_lateral_signed_2d': [-50.0, -15.0]},
                'safe_ranges': {'neck_lateral_signed_2d': [-70.0, 70.0]},
                'rep_duration': 6.0,
                'key_pose_offset': 3.0,
                'valid_rep_score': 60,
                'min_tracking_confidence': 0.2,
                'body_parts': ['CUELLO'],
                'artist': 'Rehabilitacion fisica - cuello',
                'color': (220, 130, 80),
                'complexity': 'BAJO',
                'feedback': {'waiting_start': 'Cabeza erguida, hombros relajados, mirando al frente.',
                             'go_to_target': 'Inclina la cabeza hacia la izquierda (oreja al hombro).',
                             'return_start': 'Regresa la cabeza al centro.',
                             'rep_valid': 'Repeticion valida.',
                             'rep_invalid': 'Inclina mas la cabeza manteniendo hombros quietos.',
                             'lost_tracking': 'La camara debe ver la nariz y ambos hombros.'},
                'angle_smoothing': 0.4,
                'auto_calibrate': False},
  'dedos arriba': {'id': 'dedos arriba',
                   'name': 'Extensión de Dedos',
                  'body_region': 'MANO',
                  'side': 'right',
                  'reference_video': 'rehab_references/videos/dedos arriba_valido.mp4',
                  'trajectory_json': 'rehab_references/trajectories/dedos arriba.json',
                  'tracking_type': 'hand21',
                  'landmark_schema': 'mediapipe_hand_21',
                  'evaluation_mode': 'static_wrist_alignment',
                  'validation_strategy': 'hand21_wrist_orientation_not_open_close_relaxed_step27',
                  'primary_angle': 'right_wrist_pose_angle_2d',
                  'direction': 'decreasing',
                  'active_angles': ['wrist_to_middle_tip_from_horizontal', 'avg_pip_flexion_2d', 'thumb_ip_flexion_2d'],
                  'required_landmarks': ['wrist', 'middle_mcp', 'middle_tip', 'index_mcp', 'pinky_mcp'],
                  'optional_landmarks': ['right_shoulder'],
                  'compensation_rules': [],
                  'start_ranges': {'right_wrist_pose_angle_2d': [150.0, 180.0]},
                  'target_ranges': {'right_wrist_pose_angle_2d': [100.0, 145.0]},
                  'safe_ranges': {'right_wrist_pose_angle_2d': [60.0, 180.0]},
                  'rep_duration': 6.0,
                  'key_pose_offset': 3.0,
                  'valid_rep_score': 60,
                  'min_tracking_confidence': 0.2,
                  'body_parts': ['MANO', 'DEDOS', 'MUNECA'],
                  'artist': 'Rehabilitacion fisica - mano',
                  'color': (180, 120, 255),
                  'complexity': 'BAJO',
                  'feedback': {'waiting_start': 'Muestra ANTEBRAZO y MANO. Mano recta en linea con el antebrazo.',
                               'go_to_target': 'Sube los dedos doblando la muñeca.',
                               'return_start': 'Regresa la mano recta.',
                               'rep_valid': 'Repeticion valida: orientacion correcta con dedos extendidos.',
                               'rep_invalid': 'Repeticion no valida. Revisa el rango de movimiento.',
                               'lost_tracking': 'La camara debe ver el antebrazo, la muñeca y la mano.',
                               'calibrating': 'Mano recta y quieta para calibrar...',
                               'waiting_target': 'Cambia la orientacion de la mano sin cerrar los dedos; luego vuelve '
                                                 'al objetivo.',
                               'tracking_lost': 'Ajusta encuadre: muestra la mano completa y los dedos visibles.'},
                  'angle_smoothing': 0.5,
                  'auto_calibrate': True,
                  'calib_frames': 12,
                  'calib_max_jitter': 10.0,
                  'target_delta': 28.0,
                  'return_tolerance': 10.0,
                  'safe_margin': 70.0,
                  'primary_metric': 'wrist_to_middle_tip_from_horizontal',
                  'axis_target_range': [0.0, 42.0],
                  'avg_pip_range': [162.0, 180.0],
                  'open_range': [158.0, 180.0],
                  'min_open_fingers': 4,
                  'require_thumb_open': True,
                  'thumb_open_range': [145.0, 180.0],
                  'min_tracking_quality': 0.65,
                  'min_stable_frames': 5,
                  'release_frames': 3,
                  'cooldown_frames': 5,
                  'require_release_before_count': True,
                  'release_axis_range': [34.0, 90.0],
                  'release_avg_pip_below': 158.0,
                  'release_requires_fingers_open': True,
                  'allow_no_hand_release_after_rep': True},

  'estiramiento pierna': {'id': 'estiramiento pierna',
                          'name': 'Flexión de Rodilla',
                         'body_region': 'RODILLA',
                         'side': 'left',
                         'reference_video': 'rehab_references/videos/estiramiento pierna_valido.mp4',
                         'trajectory_json': 'rehab_references/trajectories/estiramiento pierna.json',
                         'tracking_type': 'pose33',
                         'landmark_schema': 'mediapipe_pose_33',
                         'evaluation_mode': 'trajectory',
                         'validation_strategy': 'pose33_knee_flexion_decreasing',
                         'primary_angle': 'left_knee_flexion_3d',
                         'direction': 'decreasing',
                         'active_angles': ['left_knee_flexion_3d'],
                         'required_landmarks': ['left_hip', 'left_knee', 'left_ankle'],
                         'optional_landmarks': ['right_hip',
                                                'right_knee',
                                                'right_ankle',
                                                'left_shoulder',
                                                'right_shoulder'],
                         'compensation_rules': [],
                         'start_ranges': {'left_knee_flexion_3d': [150.0, 185.0]},
                         'target_ranges': {'left_knee_flexion_3d': [65.0, 125.0]},
                         'safe_ranges': {'left_knee_flexion_3d': [40.0, 190.0]},
                         'rep_duration': 6.0,
                         'key_pose_offset': 3.0,
                         'valid_rep_score': 70,
                          'min_tracking_confidence': 0.4,
                          'body_parts': ['RODILLA', 'PIERNA IZQUIERDA'],
                          'artist': 'Rehabilitacion fisica - pierna',
                          'color': (200, 160, 50),
                          'complexity': 'BAJO',
                          'feedback': {'waiting_start': 'Coloca la pierna abajo y recta.',
                                       'go_to_target': 'Dobla y levanta la pierna como en el video.',
                                       'return_start': 'Baja la pierna y vuelve a dejarla recta.',
                                       'rep_valid': 'Repeticion valida.',
                                       'rep_invalid': 'No válido. La rodilla debe doblarse claramente y volver a '
                                                      'extenderse.',
                                       'lost_tracking': 'La cámara debe ver cadera, rodilla y tobillo de la pierna que '
                                                        'se mueve.'},
                          'angle_smoothing': 0.7,
                          'auto_calibrate': False,
                          'confirmation_angle': 'left_knee_flexion_2d',
                          'confirmation_target_ranges': {'left_knee_flexion_2d': [50.0, 155.0]},
                          'min_frames_in_start': 3,
                          'min_frames_in_target': 4,
                          'min_frames_return': 3,
                         'return_tolerance': 12.0,
                         'safe_margin': 10.0},
   'estirar atras': {'id': 'estirar atras',
                     'name': 'Extensión de Tronco',
                    'body_region': 'ESPALDA',
                    'side': 'both',
                    'reference_video': 'rehab_references/videos/estirar atras_valido.mp4',
                    'trajectory_json': 'rehab_references/trajectories/estirar atras.json',
                    'tracking_type': 'pose33',
                    'landmark_schema': 'mediapipe_pose_33',
                    'evaluation_mode': 'trajectory',
                    'validation_strategy': 'single_joint_primary',
                     'primary_angle': 'trunk_lean_body_rel',
                      'direction': 'decreasing',
                      'active_angles': ['trunk_lean_body_rel', 'shoulder_alignment_2d'],
                      'required_landmarks': ['right_shoulder', 'left_shoulder'],
                      'compensation_rules': [],
                      'start_ranges': {'trunk_lean_body_rel': [130.0, 180.0]},
                      'target_ranges': {'trunk_lean_body_rel': [90.0, 135.0]},
                      'safe_ranges': {'trunk_lean_body_rel': [70.0, 180.0]},
                     'rep_duration': 6.0,
                     'key_pose_offset': 3.0,
                      'valid_rep_score': 40,
                      'min_tracking_confidence': 0.15,
                      'min_frames_in_start': 3,
                      'min_frames_in_target': 3,
                      'min_frames_return': 3,
                    'body_parts': ['ESPALDA', 'TRONCO'],
                    'artist': 'Rehabilitacion fisica - espalda',
                    'color': (180, 80, 120),
                    'complexity': 'BAJO',
                    'feedback': {'waiting_start': 'Parate erguido en posicion inicial.',
                                 'go_to_target': 'Inclinate hacia atras con control.',
                                 'return_start': 'Regresa a la posicion erguida.',
                                 'rep_valid': 'Repeticion valida.',
                                 'rep_invalid': 'Repeticion no valida. Revisa el rango de movimiento.',
                                 'lost_tracking': 'Ajusta la camara para ver bien el movimiento.'},
                     'angle_smoothing': 0.45,
                     'auto_calibrate': True,
                     'calib_frames': 12,
                     'calib_max_jitter': 10.0,
                      'target_delta': 15.0,
                      'return_tolerance': 20.0,
                      'safe_margin': 40.0},
  'estirar delante': {'id': 'estirar delante',
                       'name': 'Flexión de Tronco',
                      'body_region': 'CADERA',
                      'side': 'both',
                      'reference_video': 'rehab_references/videos/estirar delante_valido.mp4',
                      'trajectory_json': 'rehab_references/trajectories/estirar delante.json',
                      'tracking_type': 'pose33',
                      'landmark_schema': 'mediapipe_pose_33',
                      'evaluation_mode': 'trajectory',
                      'validation_strategy': 'pose33_hip_hinge_no_squat_side_view',
                      'primary_angle': 'right_hip_hinge_knee_extended_score',
                      'direction': 'increasing',
                      'active_angles': ['right_hip_hinge_knee_extended_score'],
                      'required_landmarks': ['right_shoulder', 'right_hip', 'right_knee'],
                      'compensation_rules': [],
                      'start_ranges': {'right_hip_hinge_knee_extended_score': [0.0, 35.0]},
                      'target_ranges': {'right_hip_hinge_knee_extended_score': [30.0, 125.0]},
                      'safe_ranges': {'right_hip_hinge_knee_extended_score': [0.0, 140.0]},
                      'rep_duration': 6.0,
                      'key_pose_offset': 3.0,
                      'valid_rep_score': 50,
                      'min_tracking_confidence': 0.15,
                      'body_parts': ['CADERA', 'TRONCO'],
                      'artist': 'Rehabilitacion fisica - cadera',
                      'color': (100, 100, 220),
                      'complexity': 'BAJO',
                      'feedback': {'waiting_start': 'Ponte de pie con las piernas casi rectas.',
                                   'go_to_target': 'Inclínate hacia adelante desde la cadera.',
                                   'return_start': 'Vuelve a la posición inicial de pie.',
                                   'rep_valid': 'Repeticion valida.',
                                   'rep_invalid': 'Intenta mantener la rodilla más recta.',
                                   'lost_tracking': 'Asegúrate que la cámara vea hombro, cadera y rodilla.'},
                      'angle_smoothing': 0.5,
                      'auto_calibrate': True,
                      'calib_frames': 10,
                      'calib_max_jitter': 12.0,
                      'target_delta': 25.0,
                      'return_tolerance': 20.0,
                      'safe_margin': 50.0,
                      'min_frames_in_start': 3,
                      'min_frames_in_target': 3,
                      'min_frames_return': 3},
  'hombro': {'id': 'hombro',
             'name': 'Elevación Escapular',
            'body_region': 'HOMBRO',
            'side': 'right',
            'reference_video': 'rehab_references/videos/hombro_valido.mp4',
            'trajectory_json': 'rehab_references/trajectories/hombro.json',
            'tracking_type': 'pose33',
            'landmark_schema': 'mediapipe_pose_33',
            'evaluation_mode': 'trajectory',
            'validation_strategy': 'pose33_shoulder_shrug_no_hips',
            'primary_angle': 'shoulder_head_gap_over_width_2d',
            'direction': 'decreasing',
            'active_angles': ['shoulder_head_gap_over_width_2d'],
            'required_landmarks': ['nose', 'left_shoulder', 'right_shoulder'],
            'optional_landmarks': ['left_ear', 'right_ear', 'left_hip', 'right_hip', 'left_elbow', 'right_elbow'],
            'compensation_rules': [],
            'start_ranges': {'shoulder_head_gap_over_width_2d': [80.0, 150.0]},
            'target_ranges': {'shoulder_head_gap_over_width_2d': [45.0, 78.0]},
            'safe_ranges': {'shoulder_head_gap_over_width_2d': [20.0, 180.0]},
            'rep_duration': 6.0,
            'key_pose_offset': 3.0,
            'valid_rep_score': 70,
            'min_tracking_confidence': 0.4,
            'body_parts': ['HOMBRO DERECHO'],
            'artist': 'Rehabilitacion fisica - hombro',
            'color': (0, 180, 180),
            'complexity': 'BAJO',
            'feedback': {'waiting_start': 'Relaja los hombros abajo.',
                         'go_to_target': 'Sube ambos hombros como en el video.',
                         'return_start': 'Baja los hombros a la posición inicial.',
                         'rep_valid': 'Repeticion valida.',
                         'rep_invalid': 'No válido. Sube y baja los hombros sin mover demasiado la cabeza.',
                         'lost_tracking': 'La cámara debe ver cabeza y ambos hombros.',
                         'calibrating': 'Mantente quieto en posicion inicial para calibrar...'},
            'angle_smoothing': 0.65,
            'auto_calibrate': False,
            'calib_frames': 12,
            'calib_max_jitter': 12.0,
            'target_delta': 15.0,
            'return_tolerance': 8.0,
            'safe_margin': 5.0,
            'min_frames_in_start': 5,
            'min_frames_in_target': 6,
            'min_frames_return': 5},
  'movimiento de lado': {'id': 'movimiento de lado',
                          'name': 'Rotación del Tronco (dere – frontal)',
                         'body_region': 'TRONCO',
                         'side': 'right',
                         'reference_video': 'rehab_references/videos/movimiento de lado_valido.mp4',
                         'trajectory_json': 'rehab_references/trajectories/movimiento de lado.json',
                         'tracking_type': 'pose33',
                         'landmark_schema': 'mediapipe_pose_33',
                         'evaluation_mode': 'trajectory',
                         'validation_strategy': 'single_joint_primary',
                         'primary_angle': 'shoulder_twist_signed_3d',
                         'direction': 'decreasing',
                         'active_angles': ['shoulder_twist_signed_3d', 'trunk_lean_2d'],
'required_landmarks': ['right_shoulder'],
                         'optional_landmarks': ['right_hip', 'left_hip'],
                         'compensation_rules': [],
                         'start_ranges': {'shoulder_twist_signed_3d': [-0.02, 0.02]},
                         'target_ranges': {'shoulder_twist_signed_3d': [-0.30, -0.06]},
                         'safe_ranges': {'shoulder_twist_signed_3d': [-0.40, 0.10]},
                         'rep_duration': 6.0,
                         'key_pose_offset': 3.0,
                         'valid_rep_score': 70,
                         'min_tracking_confidence': 0.2,
                         'body_parts': ['TRONCO', 'HOMBRO'],
                         'artist': 'Rehabilitacion fisica - hombro',
                         'color': (0, 180, 180),
                         'complexity': 'BAJO',
                         'feedback': {'waiting_start': 'Mantente erguido frente a la camara con brazos extendidos.',
                                      'go_to_target': 'Gira el tronco superior hacia la derecha.',
                                      'return_start': 'Regresa al centro.',
                                      'rep_valid': 'Repeticion valida.',
                                      'rep_invalid': 'Repeticion no valida. Gira solo el tronco, no las caderas.',
                                      'lost_tracking': 'Ajusta la camara para ver ambos hombros.'},
                          'angle_smoothing': 0.45,
                          'auto_calibrate': True,
                          'calib_frames': 15,
                          'calib_max_jitter': 0.03,
                          'target_delta': 0.20,
                          'return_tolerance': 0.04,
                          'safe_margin': 0.30,
                          'min_frames_in_target': 5,
                          'min_frames_in_start': 4,
                          'min_frames_return': 3},
  'movimiento de lado ezq': {'id': 'movimiento de lado ezq',
                               'name': 'Rotación del Tronco (izq– frontal)',
                              'body_region': 'TRONCO',
                              'side': 'left',
                              'reference_video': 'rehab_references/videos/movimiento de lado ezq_valido.mp4',
                              'trajectory_json': 'rehab_references/trajectories/movimiento de lado ezq.json',
                              'tracking_type': 'pose33',
                              'landmark_schema': 'mediapipe_pose_33',
                              'evaluation_mode': 'trajectory',
                              'validation_strategy': 'single_joint_primary',
                              'primary_angle': 'shoulder_twist_signed_3d',
                              'direction': 'increasing',
                              'active_angles': ['shoulder_twist_signed_3d', 'trunk_lean_2d'],
                     'required_landmarks': ['right_shoulder', 'right_hip'],
                              'optional_landmarks': ['right_hip', 'left_hip'],
                              'compensation_rules': [],
                              'start_ranges': {'shoulder_twist_signed_3d': [-0.02, 0.02]},
                              'target_ranges': {'shoulder_twist_signed_3d': [0.06, 0.30]},
                              'safe_ranges': {'shoulder_twist_signed_3d': [-0.10, 0.40]},
                              'rep_duration': 6.0,
                              'key_pose_offset': 3.0,
                              'valid_rep_score': 70,
                              'min_tracking_confidence': 0.2,
                              'body_parts': ['TRONCO', 'HOMBRO'],
                              'artist': 'Rehabilitacion fisica - hombro',
                              'color': (0, 180, 180),
                              'complexity': 'BAJO',
                              'feedback': {'waiting_start': 'Mantente erguido frente a la camara con brazos extendidos.',
                                           'go_to_target': 'Gira el tronco superior hacia la izquierda.',
                                           'return_start': 'Regresa al centro.',
                                           'rep_valid': 'Repeticion valida.',
                                           'rep_invalid': 'Repeticion no valida. Gira solo el tronco, no las caderas.',
                                           'lost_tracking': 'Ajusta la camara para ver ambos hombros.'},
                              'angle_smoothing': 0.45,
                              'auto_calibrate': True,
                              'calib_frames': 15,
                              'calib_max_jitter': 0.03,
                              'target_delta': 0.20,
                              'return_tolerance': 0.04,
                              'safe_margin': 0.30,
                              'min_frames_in_target': 5,
                              'min_frames_in_start': 4,
                              'min_frames_return': 3},

  'pierna movimiento': {'id': 'pierna movimiento',
                          'name': 'Rotación Externa de Rodilla',
                         'body_region': 'CADERA',
                         'side': 'right',
                         'reference_video': 'rehab_references/videos/pierna movimiento_valido.mp4',
                         'trajectory_json': 'rehab_references/trajectories/pierna movimiento.json',
                         'tracking_type': 'pose33',
                         'landmark_schema': 'mediapipe_pose_33',
                         'evaluation_mode': 'trajectory',
                         'validation_strategy': 'single_joint_primary',
                      'primary_angle': 'right_knee_rotation_2d',
                      'direction': 'increasing',
                      'active_angles': ['right_knee_rotation_2d', 'right_hip_abduction_full_2d', 'right_hip_flexion_2d', 'trunk_lean_2d', 'shoulder_alignment_2d'],
                      'required_landmarks': ['right_knee', 'right_foot_index', 'left_shoulder', 'right_shoulder'],
                         'optional_landmarks': ['right_ankle', 'right_foot_index'],
                         'compensation_rules': [],
                         'start_ranges': {'right_hip_abduction_full_2d': [0.0, 20.0]},
                         'target_ranges': {'right_hip_abduction_full_2d': [20.0, 60.0]},
                         'safe_ranges': {'right_hip_abduction_full_2d': [0.0, 90.0]},
                         'rep_duration': 6.0,
                         'key_pose_offset': 3.0,
                         'valid_rep_score': 70,
                         'min_tracking_confidence': 0.35,
                         'body_parts': ['CADERA', 'PIERNA DERECHA', 'MUSLO'],
                         'artist': 'Rehabilitacion fisica - cadera',
                         'color': (100, 100, 220),
                         'complexity': 'BAJO',
                         'feedback': {'waiting_start': 'Siéntate derecho, piernas juntas frente a la camara.',
                                      'go_to_target': 'Abre la pierna derecha hacia un lado (abduccion).',
                                      'return_start': 'Regresa la pierna derecha a la posicion inicial.',
                                      'rep_valid': 'Repeticion valida.',
                                      'rep_invalid': 'Repeticion no valida. Abre mas la pierna derecha hacia el lado.',
                                      'lost_tracking': 'Ajusta la camara para ver bien la cadera y la rodilla derecha.'},
                         'angle_smoothing': 0.4,
                         'auto_calibrate': True,
                         'calib_frames': 15,
                         'calib_max_jitter': 8.0,
                         'target_delta': 18.0,
                         'return_tolerance': 6.0,
                         'safe_margin': 45.0},
  'estirar pierna delante': {'id': 'estirar pierna delante',
                              'name': 'Extensión de Rodilla',
                             'body_region': 'RODILLA',
                             'side': 'right',
                             'reference_video': 'rehab_references/videos/estirar pierna delante_valido.mp4',
                             'trajectory_json': 'rehab_references/trajectories/estirar pierna delante.json',
                             'tracking_type': 'pose33',
                             'landmark_schema': 'mediapipe_pose_33',
                             'evaluation_mode': 'trajectory',
                             'validation_strategy': 'single_joint_primary',
                             'primary_angle': 'right_knee_flexion_weighted_3d',
                             'direction': 'increasing',
                             'active_angles': ['right_knee_flexion_weighted_3d', 'trunk_lean_2d', 'shoulder_alignment_2d'],
                             'required_landmarks': ['right_hip', 'right_knee', 'right_ankle'],
                             'optional_landmarks': ['right_wrist', 'left_shoulder', 'left_hip'],
                             'compensation_rules': [],
                             'start_ranges': {'right_knee_flexion_weighted_3d': [111.81, 131.81]},
                             'target_ranges': {'right_knee_flexion_weighted_3d': [151.2, 171.2]},
                             'safe_ranges': {'right_knee_flexion_weighted_3d': [89.23, 180.0]},
                             'rep_duration': 6.0,
                             'key_pose_offset': 3.0,
                             'valid_rep_score': 70,
                             'min_tracking_confidence': 0.35,
                             'body_parts': ['RODILLA DERECHA', 'PIERNA'],
                             'artist': 'Rehabilitacion fisica - pierna',
                             'color': (200, 160, 50),
                             'complexity': 'BAJO',
                             'feedback': {'waiting_start': 'Manten la rodilla doblada en posicion inicial.',
                                          'go_to_target': 'Extiende la pierna al frente.',
                                          'return_start': 'Dobla la rodilla de regreso.',
                                          'rep_valid': 'Repeticion valida.',
                                          'rep_invalid': 'Repeticion no valida. Revisa el rango de movimiento.',
                                          'lost_tracking': 'Ajusta la camara para ver bien el movimiento.'},
                             'angle_smoothing': 0.6,
                             'auto_calibrate': True,
                             'calib_frames': 12,
                             'calib_max_jitter': 12.0,
                             'target_delta': 30.0,
                             'return_tolerance': 15.0,
                             'safe_margin': 84.4},
  'rotacion mano': {'id': 'rotacion mano',
                    'name': 'Circunducción de Muñeca',
                   'body_region': 'MANO',
                   'side': 'right',
                   'reference_video': 'rehab_references/videos/rotacion mano.mp4',
                   'trajectory_json': 'rehab_references/trajectories/rotacion mano.json',
                   'tracking_type': 'hand21',
                   'landmark_schema': 'mediapipe_hand_21',
                   'evaluation_mode': 'trajectory',
                   'validation_strategy': 'single_joint_primary',
                    'primary_angle': 'hand_rotation_2d',
                    'direction': 'increasing',
                    'active_angles': ['hand_rotation_roll', 'hand_rotation_2d'],
                    'required_landmarks': ['wrist', 'middle_mcp', 'index_mcp', 'pinky_mcp'],
                    'optional_landmarks': [],
                    'compensation_rules': [],
                    'start_ranges': {'hand_rotation_2d': [0.0, 360.0]},
                    'target_ranges': {'hand_rotation_2d': [0.0, 360.0]},
                    'safe_ranges': {'hand_rotation_2d': [0.0, 360.0]},
                    'min_hand_detection_confidence': 0.25,
                    'min_hand_presence_confidence': 0.25,
                   'rep_duration': 6.0,
                   'key_pose_offset': 3.0,
                   'valid_rep_score': 70,
                   'min_tracking_confidence': 0.35,
                   'body_parts': ['MUNECA', 'MANO DERECHA'],
                   'artist': 'Rehabilitacion fisica - mano',
                   'color': (180, 120, 255),
                   'complexity': 'BAJO',
                   'feedback': {'waiting_start': 'Muestra la mano abierta frente a la camara. Mano quieta para calibrar.',
                                'go_to_target': 'Gira la muñeca lentamente (prono-supinacion).',
                                'return_start': 'Regresa la mano a la posicion inicial.',
                                'rep_valid': 'Repeticion valida.',
                                'rep_invalid': 'Repeticion no valida. Gira la mano y regresa al inicio.',
                                'lost_tracking': 'La camara debe ver la muñeca, los nudillos y los dedos.',
                                'calibrating': 'Mano quieta para calibrar...'},
                   'angle_smoothing': 0.5,
                   'auto_calibrate': True,
                   'calib_frames': 12,
                   'calib_max_jitter': 10.0,
                   'target_delta': 22.0,
                   'return_tolerance': 8.0,
                    'safe_margin': 60.0},
 'abduccion_hombro': {'id': 'abduccion_hombro',
                      'name': 'Abducción de Hombro',
                      'body_region': 'HOMBRO',
                      'side': 'right',
                      'reference_video': 'rehab_references/videos/Abducción de hombro.mp4',
                      'trajectory_json': 'rehab_references/trajectories/abduccion_hombro.json',
                      'tracking_type': 'pose33',
                      'landmark_schema': 'mediapipe_pose_33',
                      'evaluation_mode': 'trajectory',
                      'validation_strategy': 'single_joint_primary',
                      'primary_angle': 'right_shoulder_abduction_body_rel',
                      'direction': 'increasing',
                      'active_angles': ['right_shoulder_abduction_body_rel', 'right_shoulder_flexion_body_rel', 'trunk_lean_2d', 'shoulder_alignment_2d'],
                      'required_landmarks': ['right_shoulder', 'right_elbow', 'left_shoulder'],
                      'optional_landmarks': ['right_wrist', 'left_elbow', 'left_hip'],
                      'compensation_rules': [],
                      'start_ranges': {'right_shoulder_abduction_body_rel': [0.0, 20.0]},
                      'target_ranges': {'right_shoulder_abduction_body_rel': [155.0, 180.0]},
                      'safe_ranges': {'right_shoulder_abduction_body_rel': [0.0, 180.0]},
                      'rep_duration': 6.0,
                      'key_pose_offset': 3.0,
                      'valid_rep_score': 70,
                      'min_tracking_confidence': 0.35,
                      'body_parts': ['HOMBRO DERECHO', 'BRAZO'],
                      'artist': 'Rehabilitacion fisica - hombro',
                      'color': (0, 180, 180),
                      'complexity': 'BAJO',
                      'feedback': {'waiting_start': 'Brazo relajado al costado del cuerpo.',
                                   'go_to_target': 'Eleva el brazo derecho lateralmente hasta donde llegues.',
                                   'return_start': 'Baja el brazo con control.',
                                   'rep_valid': 'Repeticion valida.',
                                   'rep_invalid': 'Repeticion no valida. Intenta elevar mas el brazo.',
                                   'lost_tracking': 'La camara debe ver el hombro y el brazo derecho.'},
                       'angle_smoothing': 0.4,
                       'auto_calibrate': True,
                       'calib_frames': 15,
                       'calib_max_jitter': 10.0,
                       'target_delta': 145.0,
                       'return_tolerance': 15.0,
                       'safe_margin': 25.0,
                      'min_frames_in_start': 4,
                      'min_frames_in_target': 4,
                      'min_frames_return': 3},
 'aduccion_cadera': {'id': 'aduccion_cadera',
                     'name': 'Abducción de Cadera',
                     'body_region': 'CADERA',
                     'side': 'right',
                     'reference_video': 'rehab_references/videos/Aducción de cadera.mp4',
                     'trajectory_json': 'rehab_references/trajectories/aduccion_cadera.json',
                     'tracking_type': 'pose33',
                     'landmark_schema': 'mediapipe_pose_33',
                     'evaluation_mode': 'trajectory',
                     'validation_strategy': 'single_joint_primary',
                     'primary_angle': 'right_hip_abduction_2d',
                     'direction': 'increasing',
                     'active_angles': ['right_hip_abduction_2d', 'right_hip_flexion_2d', 'trunk_lean_2d', 'shoulder_alignment_2d'],
                     'required_landmarks': ['right_hip', 'right_knee', 'left_shoulder'],
                     'optional_landmarks': ['left_hip', 'right_ankle'],
                     'compensation_rules': [],
                     'start_ranges': {'right_hip_abduction_2d': [0.0, 12.0]},
                     'target_ranges': {'right_hip_abduction_2d': [28.0, 52.0]},
                     'safe_ranges': {'right_hip_abduction_2d': [0.0, 62.0]},
                     'rep_duration': 6.0,
                     'key_pose_offset': 3.0,
                     'valid_rep_score': 70,
                     'min_tracking_confidence': 0.35,
                     'body_parts': ['CADERA', 'PIERNA DERECHA'],
                     'artist': 'Rehabilitacion fisica - cadera',
                     'color': (100, 100, 220),
                     'complexity': 'BAJO',
                     'feedback': {'waiting_start': 'Piernas juntas, frente a la camara.',
                                  'go_to_target': 'Abre la pierna derecha hacia el lado.',
                                  'return_start': 'Regresa la pierna al centro.',
                                  'rep_valid': 'Repeticion valida.',
                                  'rep_invalid': 'Repeticion no valida. Abre mas la pierna.',
                                  'lost_tracking': 'Ajusta la camara para ver cadera y rodilla derecha.'},
                     'angle_smoothing': 0.4,
                     'auto_calibrate': True,
                     'calib_frames': 15,
                     'calib_max_jitter': 8.0,
                     'target_delta': 24.0,
                     'return_tolerance': 8.0,
                     'safe_margin': 30.0,
                     'min_frames_in_start': 4,
                     'min_frames_in_target': 4,
                     'min_frames_return': 3},
 'flexion_cervical': {'id': 'flexion_cervical',
                      'name': 'Flexión Cervical',
                      'body_region': 'CUELLO',
                      'side': 'right',
                      'reference_video': 'rehab_references/videos/Flexión cervical.mp4',
                      'trajectory_json': 'rehab_references/trajectories/flexion_cervical.json',
                      'tracking_type': 'pose33',
                      'landmark_schema': 'mediapipe_pose_33',
                      'evaluation_mode': 'trajectory',
                      'validation_strategy': 'neck_primary_only',
                      'primary_angle': 'neck_extension_side_2d',
                      'direction': 'increasing',
                      'active_angles': ['neck_extension_side_2d', 'shoulder_width_2d'],
                      'required_landmarks': ['nose', 'right_shoulder', 'left_shoulder'],
                      'optional_landmarks': ['right_ear', 'left_ear'],
                      'compensation_rules': [],
                      'angle_smoothing': 0.65,
                      'auto_calibrate': True,
                      'calib_frames': 18,
                      'calib_max_jitter': 6.0,
                      'target_delta': 22.0,
                      'return_tolerance': 14.0,
                      'safe_margin': 12.0,
                      'start_ranges': {'neck_extension_side_2d': [20.0, 45.0]},
                      'target_ranges': {'neck_extension_side_2d': [40.0, 70.0]},
                      'safe_ranges': {'neck_extension_side_2d': [10.0, 80.0]},
                      'rep_duration': 6.0,
                      'key_pose_offset': 3.0,
                      'valid_rep_score': 70,
                      'min_tracking_confidence': 0.45,
                      'body_parts': ['CUELLO'],
                      'artist': 'Rehabilitacion fisica - cuello',
                      'color': (220, 130, 80),
                      'complexity': 'BAJO',
                      'feedback': {'waiting_start': 'Coloca la cabeza neutral, de lado a la camara.',
                                   'go_to_target': 'Lleva el menton al pecho lentamente.',
                                   'return_start': 'Regresa la cabeza a neutral.',
                                   'rep_valid': 'Repeticion valida.',
                                   'rep_invalid': 'No valido. Mantente de lado y mueve solo el cuello hacia adelante.',
                                   'lost_tracking': 'Camara debe ver nariz y ambos hombros.',
                                   'calibrating': 'Mantente quieto de lado con cabeza neutral para calibrar.'},
                      'min_frames_in_target': 4,
                      'min_frames_in_start': 3,
                      'min_frames_return': 3,
                      'gate_ranges': {'shoulder_width_2d': [0.0, 0.22]},
                      'gate_feedback': 'Ponte de lado a la camara. No gires el cuerpo.'},
  'inclinacion_tronco_izq': {'id': 'inclinacion_tronco_izq',
                             'name': 'Inclinación Lateral del Tronco (izq)',
                             'body_region': 'TRONCO',
                             'side': 'left',
                             'reference_video': 'rehab_references/videos/Inclinación lateral del troco (izq).mp4',
                             'trajectory_json': 'rehab_references/trajectories/inclinacion_tronco_izq.json',
                             'tracking_type': 'pose33',
                             'landmark_schema': 'mediapipe_pose_33',
                             'evaluation_mode': 'trajectory',
                             'validation_strategy': 'single_joint_primary',
                             'primary_angle': 'right_shoulder_abduction_body_rel',
                             'direction': 'increasing',
                             'active_angles': ['right_shoulder_abduction_body_rel', 'trunk_lean_signed_2d', 'trunk_lean_2d', 'shoulder_alignment_2d'],
                             'required_landmarks': ['right_shoulder', 'left_shoulder', 'right_elbow'],
                             'optional_landmarks': ['right_hip', 'left_hip'],
                             'compensation_rules': [],
                             'gate_ranges': {'trunk_lean_signed_2d': [-60.0, -5.0], 'right_elbow_flexion_2d': [120.0, 180.0]},
                             'start_ranges': {'right_shoulder_abduction_body_rel': [9.0, 29.0]},
                             'target_ranges': {'right_shoulder_abduction_body_rel': [28.0, 48.0]},
                             'safe_ranges': {'right_shoulder_abduction_body_rel': [0.0, 58.0]},
                             'rep_duration': 6.0,
                             'key_pose_offset': 3.0,
                             'valid_rep_score': 70,
                             'min_tracking_confidence': 0.2,
                             'body_parts': ['TRONCO'],
                             'artist': 'Rehabilitacion fisica - tronco',
                             'color': (180, 80, 120),
                             'complexity': 'BAJO',
                             'feedback': {'waiting_start': 'Mantente erguido frente a la camara.',
                                          'go_to_target': 'Inclina el tronco hacia la izquierda.',
                                          'return_start': 'Regresa a la posicion erguida.',
                                          'rep_valid': 'Repeticion valida.',
                                          'rep_invalid': 'Repeticion no valida. Inclina mas el tronco.',
                                          'lost_tracking': 'Ajusta la camara para ver ambos hombros.'},
                             'angle_smoothing': 0.45,
                             'auto_calibrate': True,
                             'calib_frames': 15,
                             'calib_max_jitter': 6.0,
                             'target_delta': 12.0,
                             'return_tolerance': 8.0,
                             'safe_margin': 30.0,
                             'min_frames_in_target': 4,
                             'min_frames_in_start': 3,
                             'min_frames_return': 3},
 'rotacion_interna_rodilla': {'id': 'rotacion_interna_rodilla',
                              'name': 'Rotación Interna de Rodilla',
                              'body_region': 'RODILLA',
                              'side': 'right',
                              'reference_video': 'rehab_references/videos/Rotación interna de rodilla.mp4',
                              'trajectory_json': 'rehab_references/trajectories/rotacion_interna_rodilla.json',
                              'tracking_type': 'pose33',
                              'landmark_schema': 'mediapipe_pose_33',
                              'evaluation_mode': 'trajectory',
                              'validation_strategy': 'single_joint_primary',
                              'primary_angle': 'right_hip_abduction_full_2d',
                              'direction': 'increasing',
                              'active_angles': ['right_hip_abduction_full_2d', 'right_hip_flexion_2d', 'trunk_lean_2d', 'shoulder_alignment_2d'],
                              'required_landmarks': ['right_hip', 'right_knee', 'right_foot_index', 'left_shoulder', 'right_shoulder'],
                              'optional_landmarks': ['right_ankle', 'left_hip'],
                              'compensation_rules': [],
                      'start_ranges': {'right_knee_rotation_2d': [0.0, 11.0]},
                      'target_ranges': {'right_knee_rotation_2d': [32.0, 48.0]},
                      'safe_ranges': {'right_knee_rotation_2d': [0.0, 56.0]},
                              'rep_duration': 6.0,
                              'key_pose_offset': 3.0,
                              'valid_rep_score': 70,
                              'min_tracking_confidence': 0.35,
                              'body_parts': ['RODILLA', 'PIERNA DERECHA'],
                              'artist': 'Rehabilitacion fisica - rodilla',
                              'color': (200, 160, 50),
                              'complexity': 'BAJO',
                              'feedback': {'waiting_start': 'Siéntate derecho, pierna flexionada y pie derecho al frente.',
                                           'go_to_target': 'Gira la punta del pie hacia adentro (rotacion interna).',
                                           'return_start': 'Regresa el pie a la posicion inicial al frente.',
                                           'rep_valid': 'Repeticion valida.',
                                           'rep_invalid': 'Repeticion no valida. Gira mas el pie hacia adentro.',
                                           'lost_tracking': 'La camara debe ver cadera, rodilla y pie derecho.'},
                              'angle_smoothing': 0.4,
                              'auto_calibrate': True,
                              'calib_frames': 15,
                              'calib_max_jitter': 8.0,
                              'target_delta': 14.0,
                              'return_tolerance': 6.0,
                              'safe_margin': 25.0,
                              'min_frames_in_start': 4,
                              'min_frames_in_target': 4,
                              'min_frames_return': 3}}
